// Narrow, handwritten view of the Codex App Server protocol used by the
// bridge. The authoritative full bindings are generated by the installed
// Codex CLI; see scripts/check-codex-schema.ts. Keeping this boundary narrow
// prevents hundreds of generated files from leaking through the application.

export type RequestId = string | number

export interface RpcRequest {
  id: RequestId
  method: string
  params?: unknown
}

export interface RpcNotification {
  method: string
  params?: unknown
}

export interface RpcErrorBody {
  code: number
  message: string
  data?: unknown
}

export interface RpcResponse {
  id: RequestId
  result?: unknown
  error?: RpcErrorBody
}

export type OutboundMessage = RpcRequest | RpcNotification | RpcResponse

export interface ClientInfo {
  name: string
  title: string | null
  version: string
}

export interface InitializeCapabilities {
  experimentalApi: boolean
  requestAttestation: boolean
  mcpServerOpenaiFormElicitation?: boolean
  optOutNotificationMethods?: string[] | null
  extensions?: Record<string, unknown> | null
}

export interface InitializeParams {
  clientInfo: ClientInfo
  capabilities: InitializeCapabilities | null
}

export interface InitializeResult {
  userAgent: string
  codexHome: string
  platformFamily: string
  platformOs: string
}

export type ApprovalPolicy =
  | 'untrusted'
  | 'on-request'
  | 'never'
  | {
      granular: {
        sandbox_approval: boolean
        rules: boolean
        skill_approval: boolean
        request_permissions: boolean
        mcp_elicitations: boolean
      }
    }

export type ApprovalsReviewer = 'user' | 'auto_review' | 'guardian_subagent'
export type SandboxMode = 'read-only' | 'workspace-write' | 'danger-full-access'
export type SandboxPolicy =
  | { type: 'dangerFullAccess' }
  | { type: 'readOnly'; networkAccess: boolean }
  | { type: 'externalSandbox'; networkAccess: 'restricted' | 'enabled' }
  | {
      type: 'workspaceWrite'
      writableRoots: string[]
      networkAccess: boolean
      excludeTmpdirEnvVar: boolean
      excludeSlashTmp: boolean
    }
export type ReasoningSummary = 'auto' | 'concise' | 'detailed' | 'none'
export type Personality = 'none' | 'friendly' | 'pragmatic'

export type UserInput =
  | { type: 'text'; text: string; text_elements: unknown[] }
  | { type: 'image'; url: string; detail?: 'auto' | 'low' | 'high' | 'original' }
  | { type: 'localImage'; path: string; detail?: 'auto' | 'low' | 'high' | 'original' }
  | { type: 'audio'; url: string }
  | { type: 'localAudio'; path: string }
  | { type: 'skill'; name: string; path: string }
  | { type: 'mention'; name: string; path: string }

export interface ThreadStartParams {
  model?: string | null
  modelProvider?: string | null
  serviceTier?: string | null
  cwd?: string | null
  approvalPolicy?: ApprovalPolicy | null
  approvalsReviewer?: ApprovalsReviewer | null
  sandbox?: SandboxMode | null
  config?: Record<string, unknown> | null
  serviceName?: string | null
  baseInstructions?: string | null
  developerInstructions?: string | null
  personality?: Personality | null
  ephemeral?: boolean | null
  sessionStartSource?: 'startup' | 'clear' | null
  threadSource?: unknown
}

export interface ThreadResumeParams {
  threadId: string
  model?: string | null
  modelProvider?: string | null
  serviceTier?: string | null
  cwd?: string | null
  approvalPolicy?: ApprovalPolicy | null
  approvalsReviewer?: ApprovalsReviewer | null
  sandbox?: SandboxMode | null
  config?: Record<string, unknown> | null
  baseInstructions?: string | null
  developerInstructions?: string | null
  personality?: Personality | null
}

export interface ThreadReadParams {
  threadId: string
  includeTurns?: boolean
}

export interface AppServerThread {
  id: string
  [key: string]: unknown
}

export interface AppServerTurn {
  id: string
  [key: string]: unknown
}

export interface ThreadResult {
  thread: AppServerThread
  [key: string]: unknown
}

export interface ThreadReadResult {
  thread: AppServerThread
}

export interface TurnStartParams {
  threadId: string
  clientUserMessageId?: string | null
  input: UserInput[]
  cwd?: string | null
  approvalPolicy?: ApprovalPolicy | null
  approvalsReviewer?: ApprovalsReviewer | null
  sandboxPolicy?: SandboxPolicy | null
  model?: string | null
  serviceTier?: string | null
  effort?: string | null
  summary?: ReasoningSummary | null
  personality?: Personality | null
  outputSchema?: unknown
}

export interface TurnStartResult {
  turn: AppServerTurn
}

export interface TurnSteerParams {
  threadId: string
  clientUserMessageId?: string | null
  input: UserInput[]
  expectedTurnId: string
}

export interface TurnSteerResult {
  turnId: string
}

export interface TurnInterruptParams {
  threadId: string
  turnId: string
}

export interface ModelListParams {
  cursor?: string | null
  limit?: number | null
  includeHidden?: boolean | null
}

export interface ModelSummary {
  id: string
  model: string
  displayName: string
  hidden: boolean
  isDefault: boolean
  supportedReasoningEfforts?: Array<{
    reasoningEffort: string
    description: string
  }>
  defaultReasoningEffort?: string
  [key: string]: unknown
}

export interface ModelListResult {
  data: ModelSummary[]
  nextCursor: string | null
}

export interface ConfigReadParams {
  cwd?: string | null
  includeLayers?: boolean
}

export interface ConfigReadResult {
  config: {
    model: string | null
    model_reasoning_effort: string | null
    [key: string]: unknown
  }
  origins: Record<string, unknown>
  layers?: unknown[] | null
}

// Account and thread control types intentionally mirror only the stable
// fields rendered by the Telegram control plane. Unknown App Server fields
// remain available through index signatures so a compatible Codex patch can
// add metadata without forcing a bridge release.
export interface AccountReadParams {
  refreshToken?: boolean
}

export type Account =
  | { type: 'apiKey' }
  | { type: 'chatgpt'; email: string | null; planType: string }
  | { type: 'amazonBedrock'; usesCodexManagedCredentials: boolean }

export interface AccountReadResult {
  account: Account | null
  requiresOpenaiAuth: boolean
}

export type AccountLoginStartParams = { type: 'chatgptDeviceCode' }

export type AccountLoginStartResult =
  | {
      type: 'chatgptDeviceCode'
      loginId: string
      verificationUrl: string
      userCode: string
    }
  | { type: string; [key: string]: unknown }

export interface RateLimitWindow {
  usedPercent: number
  windowDurationMins: number | null
  resetsAt: number | null
}

export interface RateLimitSnapshot {
  limitId: string | null
  limitName: string | null
  primary: RateLimitWindow | null
  secondary: RateLimitWindow | null
  credits: unknown | null
  planType: string | null
  rateLimitReachedType: string | null
  [key: string]: unknown
}

export interface AccountRateLimitsResult {
  rateLimits: RateLimitSnapshot
  rateLimitsByLimitId: Record<string, RateLimitSnapshot | undefined> | null
  rateLimitResetCredits: unknown | null
}

export interface AccountUsageParams {
  threadId?: string | null
}

export interface AccountUsageResult {
  summary: {
    lifetimeTokens: number | string | null
    peakDailyTokens: number | string | null
    longestRunningTurnSec: number | string | null
    currentStreakDays: number | string | null
    longestStreakDays: number | string | null
    [key: string]: unknown
  }
  dailyUsageBuckets: Array<{
    startDate: string
    tokens: number | string
    [key: string]: unknown
  }> | null
  threadUsage?: {
    threadId: string
    estimatedUsageCreditsMicros: number | string
    estimatedUsageUsdMicros: number | string | null
    groups: unknown[]
    [key: string]: unknown
  } | null
}

export interface ThreadListParams {
  cursor?: string | null
  limit?: number | null
  sortKey?: 'created_at' | 'updated_at' | null
  sortDirection?: 'asc' | 'desc' | null
  archived?: boolean | null
  cwd?: string | string[] | null
  useStateDbOnly?: boolean
  searchTerm?: string | null
}

export interface ThreadListResult {
  data: AppServerThread[]
  nextCursor: string | null
  backwardsCursor: string | null
}

export interface ThreadSetNameParams {
  threadId: string
  name: string
}

export interface ThreadIdParams {
  threadId: string
}

export interface ThreadForkParams extends ThreadIdParams {
  lastTurnId?: string | null
  cwd?: string | null
}

export interface ReviewTargetUncommitted {
  type: 'uncommittedChanges'
}

export type ReviewTarget =
  | ReviewTargetUncommitted
  | { type: 'baseBranch'; branch: string }
  | { type: 'commit'; sha: string; title: string | null }
  | { type: 'custom'; instructions: string }

export interface ReviewStartParams {
  threadId: string
  target: ReviewTarget
  delivery?: 'inline' | 'detached' | null
}

export interface ReviewStartResult {
  turn: AppServerTurn
  reviewThreadId: string
}

export interface ServerNotification {
  method: string
  params?: unknown
}

export interface ServerRequest {
  id: RequestId
  method: string
  params?: unknown
}

export function textInput(text: string): UserInput {
  return { type: 'text', text, text_elements: [] }
}
